{% set commit_id="75985e3095ea8f12f4ba7dfac9ba38ff59f751e8" %}
{% set version="2.0.0" %}
package:
  name: stammp
  version: {{ version }}

source:
  git_url: git@github.com:soedinglab/stammp2.git
  git_rev: {{ commit_id }}

build:
  script: python setup.py install --single-version-externally-managed --record record.txt
  number: 0
  skip: True  #  [not py3k]
  entry_points:
    - stammp-bsfinder = stammp.scripts.bsfinder:run
    - stammp-preprocess = stammp.scripts.preprocess:run
    - stammp-postprocess = stammp.scripts.postprocess:main
    - stammp-normalize = stammp.scripts.normalize:run
#    - stammp-normalizeFake = stammp.scripts.normalizeFake:run
    - stammp-convert2quantile = stammp.scripts.convert2quantile:run
#    - stammp-makeCenterBothEnds = stammp.plots.makeCenterBothEnds:run
    - stammp-makeCenterBothEnds_bs = stammp.plots.makeCenterBothEnds_bs:main
    - stammp-makeKmerPerPosition = stammp.plots.makeKmerPerPosition:run
#    - stammp-remove5primeAdapter = stammp.scripts.utils.remove5primeAdapter:run
    - stammp-removePCRduplicates = stammp.scripts.utils.removePCRduplicates:run
    - stammp-makeNegSets = stammp.scripts.makeNegSets:run
    - stammp-xxmotif = stammp.scripts.xxmotif:run
    - stammp-makeKmerLogOdds = stammp.plots.makeKmerLogOdds:run
#    - stammp-makeJaccard = stammp.plots.makeJaccard:run
#    - stammp-getProcessingIndex = stammp.scripts.getProcessingIndex:run
#    - stammp-getColocalization = stammp.scripts.getColocalization:run
    - stammp-makeHeatMap = stammp.plots.makeHeatMap:run
    - stammp-makeHeatMapSmall = stammp.plots.makeHeatMapSmall:run
    - stammp-makeNucleotideProbabilities = stammp.plots.makeNucleotideProbabilities:run
    - stammp-adapter-clipper = stammp.scripts.utils.clipper53:main
#    - stammp-selectSitesInside = stammp.scripts.selectSitesInside:run
#    - stammp-selectSitesAround = stammp.scripts.selectSitesAround:run
#    - stammp-generateConfig = stammp.scripts.generate_config:main
    - stammp-bam-postprocess = stammp.scripts.bam_postprocessing:main
    - stammp-softclip-analyzer = stammp.scripts.utils.clipped_seq:main
    - stammp-gffFilterSites = stammp.scripts.filter_sites:main
    - stammp-annotate-table = stammp.scripts.utils.annotate_table:main

requirements:
  build:
    - python

  run:
    - python
    - numpy
    - scipy
    - pandas
    - matplotlib
    - seaborn
    - pysam
    - star
    - bowtie
    - samtools
    - fastqc
    - xxmotif
    - r
    - r-lsd
    - pyivtree
    - pyyaml
    - jinja2

test:
  imports:
    - stammp
    - stammp.utils

  requires:
    - nose
  commands:
    - nosetests stammp
